name: Main taski workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: Ubuntu-latest
    steps: 
    - name: Копируем код проекта
      uses: actions/checkout/@v3

    - name: Устанавливаем Python
      uses: actions/setup-python@v4
      with: 
        python-version: 3.9

    - name: Обновляем pip, устанавливаем flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.0.0 flake8-isort==6.0.0
        pip install -r ./backend/requirements.txt
    
    - name: Запускаем flake8
      run: python -m flake8 backend/
      cd backend/
      python manage.py test
